In [7]:
import pandas as pd

df = pd.read_csv("NLP_Assignment1.csv", encoding="latin1")
print(df.head())

                                              Review     Label
0  The lecture was very clear and easy to understand  Positive
1             I enjoyed working on the project today  Positive
2  The assignment helped me understand the concep...  Positive
3     Group discussion was productive and insightful  Positive
4           The professor explained doubts patiently  Positive

In [9]:
print(df.head(3))
r, c = df.shape
print("Rows:", r, "Cols:", c)

                                              Review     Label
0  The lecture was very clear and easy to understand  Positive
1             I enjoyed working on the project today  Positive
2  The assignment helped me understand the concep...  Positive
Rows: 100 Cols: 2

In [10]:
print("Cols:", list(df.columns))
print("Types:")
print(df.dtypes)

Cols: ['Review', 'Label']
Types:
Review    object
Label     object
dtype: object

In [12]:
u = df["Label"].nunique()
print("Unique labels:", u)

Unique labels: 3

In [14]:
print(df["Label"].value_counts())

Label
Neutral     40
Positive    30
Negative    30
Name: count, dtype: int64

In [16]:
df[df["Label"] == "Negative"]

                                        Review     Label
20       The lecture felt boring and confusing  Negative
21     I couldnt concentrate during the class  Negative
22             The workload feels overwhelming  Negative
23     I am stressed about pending assignments  Negative
24      The explanation was unclear and rushed  Negative
25        I missed an important deadline today  Negative
26  The lab equipment was not working properly  Negative
27        The syllabus feels too vast to cover  Negative
28                I feel tired and unmotivated  Negative
29           The test was harder than expected  Negative
30         I struggled to understand the topic  Negative
31           The schedule feels poorly planned  Negative
32                I wasted a lot of time today  Negative
33             The instructions were confusing  Negative
34         I am falling behind in this subject  Negative
35                  The class pace is too fast  Negative
36              I feel anxious about the exams  Negative
37             The group work was unproductive  Negative
38         The lecture slides were poorly made  Negative
39         I did not understand anything today  Negative
75                   I learned a bit, not much  Negative
76                   I revised previous topics  Negative
77                     The pace was manageable  Negative
78                   The session ended quickly  Negative
79                The lecture was okay overall  Negative
90                 I revised a subject briefly  Negative
91           The lecture was conducted on time  Negative
92         I studied but didnt track progress  Negative
93    I practiced questions without difficulty  Negative
94            I listened but didnt ask doubts  Negative

In [18]:
df["cc"] = df["Review"].str.len()

In [20]:
df["wc"] = df["Review"].str.split().str.len()

In [22]:
df["lc"] = df["Review"].str.lower()

In [24]:
df["cc"] = df["Review"].str.len()
df.head(3)

,Review,Label,cc,wc,lc
0,The lecture was very clear and easy to understand,Positive,49,9,the lecture was very clear and easy to understand
1,I enjoyed working on the project today,Positive,38,7,i enjoyed working on the project today
2,The assignment helped me understand the concep...,Positive,54,8,the assignment helped me understand the concep...

In [26]:
df["label"] = df["Label"].str.lower()

In [27]:
mp = {"positive":1, "neutral":0, "negative":-1}
df["enc"] = df["label"].map(mp)

In [28]:
df.head(5)

,Review,Label,cc,wc,lc,label,enc
0,The lecture was very clear and easy to understand,Positive,49,9,the lecture was very clear and easy to understand,positive,1
1,I enjoyed working on the project today,Positive,38,7,i enjoyed working on the project today,positive,1
2,The assignment helped me understand the concep...,Positive,54,8,the assignment helped me understand the concep...,positive,1
3,Group discussion was productive and insightful,Positive,46,6,group discussion was productive and insightful,positive,1
4,The professor explained doubts patiently,Positive,40,5,the professor explained doubts patiently,positive,1

In [29]:
df.sort_values(by="wc", ascending=False)

,Review,Label,cc,wc,lc,label,enc
0,The lecture was very clear and easy to understand,Positive,49,9,the lecture was very clear and easy to understand,positive,1
5,I managed to complete all my tasks on time,Positive,42,9,i managed to complete all my tasks on time,positive,1
2,The assignment helped me understand the concep...,Positive,54,8,the assignment helped me understand the concep...,positive,1
70,The subject is interesting but needs more revi...,Positive,50,8,the subject is interesting but needs more revi...,positive,1
34,I am falling behind in this subject,Negative,35,7,i am falling behind in this subject,negative,-1
...,...,...,...,...,...,...,...
87,I read reference material,Positive,25,4,i read reference material,positive,1
85,I studied ML concepts,Positive,21,4,i studied ml concepts,positive,1
96,The schedule was average,Neutral,24,4,the schedule was average,neutral,0
97,The professor covered topics,Neutral,28,4,the professor covered topics,neutral,0
99,I practiced PCA problems,Neutral,24,4,i practiced pca problems,neutral,0

In [30]:
df.nlargest(3, "wc")

,Review,Label,cc,wc,lc,label,enc
0,The lecture was very clear and easy to understand,Positive,49,9,the lecture was very clear and easy to understand,positive,1
5,I managed to complete all my tasks on time,Positive,42,9,i managed to complete all my tasks on time,positive,1
2,The assignment helped me understand the concep...,Positive,54,8,the assignment helped me understand the concep...,positive,1

In [31]:
df[(df["wc"] > 6) & (df["label"] == "positive")]

,Review,Label,cc,wc,lc,label,enc
0,The lecture was very clear and easy to understand,Positive,49,9,the lecture was very clear and easy to understand,positive,1
1,I enjoyed working on the project today,Positive,38,7,i enjoyed working on the project today,positive,1
2,The assignment helped me understand the concep...,Positive,54,8,the assignment helped me understand the concep...,positive,1
5,I managed to complete all my tasks on time,Positive,42,9,i managed to complete all my tasks on time,positive,1
6,The lab session went smoothly without issues,Positive,44,7,the lab session went smoothly without issues,positive,1
9,I feel confident about the upcoming exam,Positive,40,7,i feel confident about the upcoming exam,positive,1
11,I learned something new and useful today,Positive,40,7,i learned something new and useful today,positive,1
13,I stayed focused throughout the study session,Positive,45,7,i stayed focused throughout the study session,positive,1
16,I understood the topic faster than expected,Positive,43,7,i understood the topic faster than expected,positive,1
70,The subject is interesting but needs more revi...,Positive,50,8,the subject is interesting but needs more revi...,positive,1

In [32]:
df.groupby("label")["wc"].mean()

label
negative    5.600
neutral     5.275
positive    6.000
Name: wc, dtype: float64

In [33]:
df.groupby("label")["wc"].mean().idxmax()

'positive'

In [34]:
df[df["wc"] < 5].groupby("label")["wc"].count()

label
negative    5
neutral     8
positive    4
Name: wc, dtype: int64

In [36]:
df.index = df.index + 1

In [38]:
df = df.rename(columns={"text":"review_text", "label":"sentiment"})

In [39]:
df.head(5)

,Review,Label,cc,wc,lc,sentiment,enc
2,The lecture was very clear and easy to understand,Positive,49,9,the lecture was very clear and easy to understand,positive,1
3,I enjoyed working on the project today,Positive,38,7,i enjoyed working on the project today,positive,1
4,The assignment helped me understand the concep...,Positive,54,8,the assignment helped me understand the concep...,positive,1
5,Group discussion was productive and insightful,Positive,46,6,group discussion was productive and insightful,positive,1
6,The professor explained doubts patiently,Positive,40,5,the professor explained doubts patiently,positive,1

In [42]:
df.at[6, "sentiment"] = "positive"

In [43]:
dfp = df[df["sentiment"] == "positive"]

In [44]:
df.head(5)

,Review,Label,cc,wc,lc,sentiment,enc
2,The lecture was very clear and easy to understand,Positive,49,9,the lecture was very clear and easy to understand,positive,1
3,I enjoyed working on the project today,Positive,38,7,i enjoyed working on the project today,positive,1
4,The assignment helped me understand the concep...,Positive,54,8,the assignment helped me understand the concep...,positive,1
5,Group discussion was productive and insightful,Positive,46,6,group discussion was productive and insightful,positive,1
6,The professor explained doubts patiently,Positive,40,5,the professor explained doubts patiently,positive,1

In [45]:
df.to_csv("NLP_Assignment1_cleaned.csv", index=True, encoding="utf-8")

In [47]:
df2 = pd.read_csv("NLP_Assignment1_cleaned.csv", encoding="latin1")
df2.head()
df2.dtypes

Unnamed: 0     int64
Review        object
Label         object
cc             int64
wc             int64
lc            object
sentiment     object
enc            int64
dtype: object